/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GSessionIdRouteImport } from './routes/g.$sessionId'
import { Route as BSessionIdRouteImport } from './routes/b.$sessionId'
import { Route as ApiRealtimeConfigRouteImport } from './routes/api/realtime-config'
import { Route as GSessionIdIndexRouteImport } from './routes/g.$sessionId.index'
import { Route as BSessionIdIndexRouteImport } from './routes/b.$sessionId.index'
import { Route as GSessionIdResultRouteImport } from './routes/g.$sessionId.result'
import { Route as BSessionIdResultRouteImport } from './routes/b.$sessionId.result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GSessionIdRoute = GSessionIdRouteImport.update({
  id: '/g/$sessionId',
  path: '/g/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const BSessionIdRoute = BSessionIdRouteImport.update({
  id: '/b/$sessionId',
  path: '/b/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeConfigRoute = ApiRealtimeConfigRouteImport.update({
  id: '/api/realtime-config',
  path: '/api/realtime-config',
  getParentRoute: () => rootRouteImport,
} as any)
const GSessionIdIndexRoute = GSessionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GSessionIdRoute,
} as any)
const BSessionIdIndexRoute = BSessionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BSessionIdRoute,
} as any)
const GSessionIdResultRoute = GSessionIdResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => GSessionIdRoute,
} as any)
const BSessionIdResultRoute = BSessionIdResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => BSessionIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/realtime-config': typeof ApiRealtimeConfigRoute
  '/b/$sessionId': typeof BSessionIdRouteWithChildren
  '/g/$sessionId': typeof GSessionIdRouteWithChildren
  '/b/$sessionId/result': typeof BSessionIdResultRoute
  '/g/$sessionId/result': typeof GSessionIdResultRoute
  '/b/$sessionId/': typeof BSessionIdIndexRoute
  '/g/$sessionId/': typeof GSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/realtime-config': typeof ApiRealtimeConfigRoute
  '/b/$sessionId/result': typeof BSessionIdResultRoute
  '/g/$sessionId/result': typeof GSessionIdResultRoute
  '/b/$sessionId': typeof BSessionIdIndexRoute
  '/g/$sessionId': typeof GSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/realtime-config': typeof ApiRealtimeConfigRoute
  '/b/$sessionId': typeof BSessionIdRouteWithChildren
  '/g/$sessionId': typeof GSessionIdRouteWithChildren
  '/b/$sessionId/result': typeof BSessionIdResultRoute
  '/g/$sessionId/result': typeof GSessionIdResultRoute
  '/b/$sessionId/': typeof BSessionIdIndexRoute
  '/g/$sessionId/': typeof GSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/realtime-config'
    | '/b/$sessionId'
    | '/g/$sessionId'
    | '/b/$sessionId/result'
    | '/g/$sessionId/result'
    | '/b/$sessionId/'
    | '/g/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/realtime-config'
    | '/b/$sessionId/result'
    | '/g/$sessionId/result'
    | '/b/$sessionId'
    | '/g/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/api/realtime-config'
    | '/b/$sessionId'
    | '/g/$sessionId'
    | '/b/$sessionId/result'
    | '/g/$sessionId/result'
    | '/b/$sessionId/'
    | '/g/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRealtimeConfigRoute: typeof ApiRealtimeConfigRoute
  BSessionIdRoute: typeof BSessionIdRouteWithChildren
  GSessionIdRoute: typeof GSessionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$sessionId': {
      id: '/g/$sessionId'
      path: '/g/$sessionId'
      fullPath: '/g/$sessionId'
      preLoaderRoute: typeof GSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$sessionId': {
      id: '/b/$sessionId'
      path: '/b/$sessionId'
      fullPath: '/b/$sessionId'
      preLoaderRoute: typeof BSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime-config': {
      id: '/api/realtime-config'
      path: '/api/realtime-config'
      fullPath: '/api/realtime-config'
      preLoaderRoute: typeof ApiRealtimeConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$sessionId/': {
      id: '/g/$sessionId/'
      path: '/'
      fullPath: '/g/$sessionId/'
      preLoaderRoute: typeof GSessionIdIndexRouteImport
      parentRoute: typeof GSessionIdRoute
    }
    '/b/$sessionId/': {
      id: '/b/$sessionId/'
      path: '/'
      fullPath: '/b/$sessionId/'
      preLoaderRoute: typeof BSessionIdIndexRouteImport
      parentRoute: typeof BSessionIdRoute
    }
    '/g/$sessionId/result': {
      id: '/g/$sessionId/result'
      path: '/result'
      fullPath: '/g/$sessionId/result'
      preLoaderRoute: typeof GSessionIdResultRouteImport
      parentRoute: typeof GSessionIdRoute
    }
    '/b/$sessionId/result': {
      id: '/b/$sessionId/result'
      path: '/result'
      fullPath: '/b/$sessionId/result'
      preLoaderRoute: typeof BSessionIdResultRouteImport
      parentRoute: typeof BSessionIdRoute
    }
  }
}

interface BSessionIdRouteChildren {
  BSessionIdResultRoute: typeof BSessionIdResultRoute
  BSessionIdIndexRoute: typeof BSessionIdIndexRoute
}

const BSessionIdRouteChildren: BSessionIdRouteChildren = {
  BSessionIdResultRoute: BSessionIdResultRoute,
  BSessionIdIndexRoute: BSessionIdIndexRoute,
}

const BSessionIdRouteWithChildren = BSessionIdRoute._addFileChildren(
  BSessionIdRouteChildren,
)

interface GSessionIdRouteChildren {
  GSessionIdResultRoute: typeof GSessionIdResultRoute
  GSessionIdIndexRoute: typeof GSessionIdIndexRoute
}

const GSessionIdRouteChildren: GSessionIdRouteChildren = {
  GSessionIdResultRoute: GSessionIdResultRoute,
  GSessionIdIndexRoute: GSessionIdIndexRoute,
}

const GSessionIdRouteWithChildren = GSessionIdRoute._addFileChildren(
  GSessionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRealtimeConfigRoute: ApiRealtimeConfigRoute,
  BSessionIdRoute: BSessionIdRouteWithChildren,
  GSessionIdRoute: GSessionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
